#pragma once

#ifndef __TOKEN_TYPE_HPP__
#define __TOKEN_TYPE_HPP__

enum    TokenType {
    PARAMETER, NUMBER, LEFT_BRACE, RIGHT_BRACE, SEMICOLON, SERVER_BLOCK, LISTEN,
    ROOT, CLIENT_MAX_BODY_SIZE, ERROR_PAGE, INDEX, LOCATION, AUTOINDEX,
    ALLOW_METHODS, RETURN, INCLUDE, PATH, CGI_PATH, SERV_NAME
};

#endif
